// <auto-generated />
namespace StoreDB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _20181218整理TableGuid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20181218整理TableGuid));
        
        string IMigrationMetadata.Id
        {
            get { return "201812180334128_20181218整理TableGuid"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
