// <auto-generated />
namespace StoreDB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Back15_ModifyMember : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Back15_ModifyMember));
        
        string IMigrationMetadata.Id
        {
            get { return "201807210828530_Back15_ModifyMember"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
