// <auto-generated />
namespace StoreDB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Back07_StaticHtml_PictureInfo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Back07_StaticHtml_PictureInfo));
        
        string IMigrationMetadata.Id
        {
            get { return "201805210949468_Back07_StaticHtml_PictureInfo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
