// <auto-generated />
namespace StoreDB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Back_18_Modify_MemberFiled : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Back_18_Modify_MemberFiled));
        
        string IMigrationMetadata.Id
        {
            get { return "201901220613296_Back_18_Modify_MemberFiled"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
