// <auto-generated />
namespace StoreDB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Back_17_membreAndZipCode : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Back_17_membreAndZipCode));
        
        string IMigrationMetadata.Id
        {
            get { return "201901210959459_Back_17_membreAndZipCode"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
